In [1]:
import pandas as pd
import numpy as np

# Load

In [2]:
ual = pd.read_csv('anime_data/animelists_cleaned.csv')

In [3]:
anime = pd.read_csv('anime_data/anime_cleaned.csv')

In [4]:
# anime_syn = pd.read_csv('anime_data/anime_with_synopsis.csv')

In [5]:
users = pd.read_csv('anime_data/users_cleaned.csv')

In [6]:
# anime = anime.merge(anime_syn[['MAL_ID','sypnopsis']],left_on='anime_id',right_on='MAL_ID',how='left').drop(columns=['MAL_ID'])

lets use a subset of these data for a simple PoC

In [7]:
ual.head()

,username,anime_id,my_watched_episodes,my_start_date,my_finish_date,my_score,my_status,my_rewatching,my_rewatching_ep,my_last_updated,my_tags
0,karthiga,21,586,0000-00-00,0000-00-00,9,1,NaN,0,2013-03-03 10:52:53,NaN
1,karthiga,59,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-10 13:54:51,NaN
2,karthiga,74,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-04-27 16:43:35,NaN
3,karthiga,120,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-03 10:53:57,NaN
4,karthiga,178,26,0000-00-00,0000-00-00,7,2,0.0,0,2013-03-27 15:59:13,NaN

In [6]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6668 entries, 0 to 6667
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   anime_id         6668 non-null   int64
 1   title            6668 non-null   object
 2   title_english    3438 non-null   object
 3   title_japanese   6663 non-null   object
 4   title_synonyms   4481 non-null   object
 5   image_url        6666 non-null   object
 6   type             6668 non-null   object
 7   source           6668 non-null   object
 8   episodes         6668 non-null   int64
 9   status           6668 non-null   object
 10  airing           6668 non-null   bool
 11  aired_string     6668 non-null   object
 12  aired            6668 non-null   object
 13  duration         6668 non-null   object
 14  rating           6668 non-null   object
 15  score            6668 non-null   float64
 16  scored_by        6668 non-null   int64
 17  rank             6312 non-null   float64
 18  popularity       6668 non-null   int64
 19  members          6668 non-null   int64
 20  favorites        6668 non-null   int64
 21  background       813 non-null    object
 22  premiered        2966 non-null   object
 23  broadcast        2980 non-null   object
 24  related          6668 non-null   object
 25  producer         4402 non-null   object
 26  licensor         2787 non-null   object
 27  studio           6668 non-null   object
 28  genre            6664 non-null   object
 29  opening_theme    6668 non-null   object
 30  ending_theme     6668 non-null   object
 31  duration_min     6668 non-null   float64
 32  aired_from_year  6668 non-null   float64
dtypes: bool(1), float64(4), int64(6), object(22)
memory usage: 1.6+ MB

In [8]:
anime.head()

,anime_id,title,title_english,title_japanese,title_synonyms,image_url,type,source,episodes,status,...,broadcast,related,producer,licensor,studio,genre,opening_theme,ending_theme,duration_min,aired_from_year
0,11013,Inu x Boku SS,Inu X Boku Secret Service,妖狐×僕SS,Youko x Boku SS,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,...,Fridays at Unknown,"{'Adaptation': [{'mal_id': 17207, 'type': 'man...","Aniplex, Square Enix, Mainichi Broadcasting Sy...",Sentai Filmworks,David Production,"Comedy, Supernatural, Romance, Shounen","['""Nirvana"" by MUCC']","['#1: ""Nirvana"" by MUCC (eps 1, 11-12)', '#2: ...",24.0,2012.0
1,2104,Seto no Hanayome,My Bride is a Mermaid,瀬戸の花嫁,The Inland Sea Bride,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 759, 'type': 'manga...","TV Tokyo, AIC, Square Enix, Sotsu",Funimation,Gonzo,"Comedy, Parody, Romance, School, Shounen","['""Romantic summer"" by SUN&LUNAR']","['#1: ""Ashita e no Hikari (明日への光)"" by Asuka Hi...",24.0,2007.0
2,5262,Shugo Chara!! Doki,Shugo Chara!! Doki,しゅごキャラ！！どきっ,"Shugo Chara Ninenme, Shugo Chara! Second Year",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 101, 'type': 'manga...","TV Tokyo, Sotsu",NaN,Satelight,"Comedy, Magic, School, Shoujo","['#1: ""Minna no Tamago (みんなのたまご)"" by Shugo Cha...","['#1: ""Rottara Rottara (ロッタラ ロッタラ)"" by Buono! ...",24.0,2008.0
3,721,Princess Tutu,Princess Tutu,プリンセスチュチュ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,38,Finished Airing,...,Fridays at Unknown,"{'Adaptation': [{'mal_id': 1581, 'type': 'mang...","Memory-Tech, GANSIS, Marvelous AQL",ADV Films,Hal Film Maker,"Comedy, Drama, Magic, Romance, Fantasy","['""Morning Grace"" by Ritsuko Okazaki']","['""Watashi No Ai Wa Chiisaikeredo"" by Ritsuko ...",16.0,2002.0
4,12365,Bakuman. 3rd Season,Bakuman.,バクマン。,Bakuman Season 3,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,25,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 9711, 'type': 'mang...","NHK, Shueisha",NaN,J.C.Staff,"Comedy, Drama, Romance, Shounen","['#1: ""Moshimo no Hanashi (もしもの話)"" by nano.RIP...","['#1: ""Pride on Everyday"" by Sphere (eps 1-13)...",24.0,2012.0

# Explore

## Anime

In [7]:
anime.head()

,anime_id,title,title_english,title_japanese,title_synonyms,image_url,type,source,episodes,status,...,related,producer,licensor,studio,genre,opening_theme,ending_theme,duration_min,aired_from_year,sypnopsis
0,11013,Inu x Boku SS,Inu X Boku Secret Service,妖狐×僕SS,Youko x Boku SS,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,...,"{'Adaptation': [{'mal_id': 17207, 'type': 'man...","Aniplex, Square Enix, Mainichi Broadcasting Sy...",Sentai Filmworks,David Production,"Comedy, Supernatural, Romance, Shounen","['""Nirvana"" by MUCC']","['#1: ""Nirvana"" by MUCC (eps 1, 11-12)', '#2: ...",24.0,2012.0,chiyo Shirakiin is the sheltered daughter of a...
1,2104,Seto no Hanayome,My Bride is a Mermaid,瀬戸の花嫁,The Inland Sea Bride,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,...,"{'Adaptation': [{'mal_id': 759, 'type': 'manga...","TV Tokyo, AIC, Square Enix, Sotsu",Funimation,Gonzo,"Comedy, Parody, Romance, School, Shounen","['""Romantic summer"" by SUN&LUNAR']","['#1: ""Ashita e no Hikari (明日への光)"" by Asuka Hi...",24.0,2007.0,"During his summer vacation, middle school stud..."
2,5262,Shugo Chara!! Doki,Shugo Chara!! Doki,しゅごキャラ！！どきっ,"Shugo Chara Ninenme, Shugo Chara! Second Year",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,...,"{'Adaptation': [{'mal_id': 101, 'type': 'manga...","TV Tokyo, Sotsu",NaN,Satelight,"Comedy, Magic, School, Shoujo","['#1: ""Minna no Tamago (みんなのたまご)"" by Shugo Cha...","['#1: ""Rottara Rottara (ロッタラ ロッタラ)"" by Buono! ...",24.0,2008.0,Now Utau has left Easter and restarted her sin...
3,721,Princess Tutu,Princess Tutu,プリンセスチュチュ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,38,Finished Airing,...,"{'Adaptation': [{'mal_id': 1581, 'type': 'mang...","Memory-Tech, GANSIS, Marvelous AQL",ADV Films,Hal Film Maker,"Comedy, Drama, Magic, Romance, Fantasy","['""Morning Grace"" by Ritsuko Okazaki']","['""Watashi No Ai Wa Chiisaikeredo"" by Ritsuko ...",16.0,2002.0,"In a fairy tale come to life, the clumsy, swee..."
4,12365,Bakuman. 3rd Season,Bakuman.,バクマン。,Bakuman Season 3,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,25,Finished Airing,...,"{'Adaptation': [{'mal_id': 9711, 'type': 'mang...","NHK, Shueisha",NaN,J.C.Staff,"Comedy, Drama, Romance, Shounen","['#1: ""Moshimo no Hanashi (もしもの話)"" by nano.RIP...","['#1: ""Pride on Everyday"" by Sphere (eps 1-13)...",24.0,2012.0,"Onto their third serialization, manga duo Mori..."

In [8]:
anime.isnull().sum()

anime_id              0
title                 0
title_english      3230
title_japanese        5
title_synonyms     2187
image_url             2
type                  0
source                0
episodes              0
status                0
airing                0
aired_string          0
aired                 0
duration              0
rating                0
score                 0
scored_by             0
rank                356
popularity            0
members               0
favorites             0
background         5855
premiered          3702
broadcast          3688
related               0
producer           2266
licensor           3881
studio                0
genre                 4
opening_theme         0
ending_theme          0
duration_min          0
aired_from_year       0
sypnopsis           345
dtype: int64

In [9]:
anime.columns

Index(['anime_id', 'title', 'title_english', 'title_japanese',
       'title_synonyms', 'image_url', 'type', 'source', 'episodes', 'status',
       'airing', 'aired_string', 'aired', 'duration', 'rating', 'score',
       'scored_by', 'rank', 'popularity', 'members', 'favorites', 'background',
       'premiered', 'broadcast', 'related', 'producer', 'licensor', 'studio',
       'genre', 'opening_theme', 'ending_theme', 'duration_min',
       'aired_from_year', 'sypnopsis'],
      dtype='object')

In [43]:
anime.iloc[0]['related']

"{'Adaptation': [{'mal_id': 17207, 'type': 'manga', 'url': 'https://myanimelist.net/manga/17207/Inu_x_Boku_SS', 'title': 'Inu x Boku SS'}], 'Sequel': [{'mal_id': 13403, 'type': 'anime', 'url': 'https://myanimelist.net/anime/13403/Inu_x_Boku_SS_Special', 'title': 'Inu x Boku SS Special'}]}"

In [11]:
anime.type.value_counts()

TV         2980
OVA        1345
Special     929
Movie       908
ONA         408
Music        98
Name: type, dtype: int64

In [10]:
user.head()

,username,user_id,user_watching,user_completed,user_onhold,user_dropped,user_plantowatch,user_days_spent_watching,gender,location,birth_date,access_rank,join_date,last_online,stats_mean_score,stats_rewatched,stats_episodes
0,karthiga,2255153,3,49,1,0,0,55.091667,Female,"Chennai, India",1990-04-29 00:00:00,NaN,2013-03-03 00:00:00,2014-02-04 01:32:00,7.43,0.0,3391
1,Damonashu,37326,45,195,27,25,59,82.574306,Male,"Detroit,Michigan",1991-08-01 00:00:00,NaN,2008-02-13 00:00:00,2017-07-10 06:52:54,6.15,6.0,4903
2,bskai,228342,25,414,2,5,11,159.483333,Male,"Nayarit, Mexico",1990-12-14 00:00:00,NaN,2009-08-31 00:00:00,2014-05-12 16:35:00,8.27,1.0,9701
3,terune_uzumaki,327311,5,5,0,0,0,11.394444,Female,"Malaysia, Kuantan",1998-08-24 00:00:00,NaN,2010-05-10 00:00:00,2012-10-18 19:06:00,9.70,6.0,697
4,Bas_G,5015094,35,114,6,20,175,30.458333,Male,"Nijmegen, Nederland",1999-10-24 00:00:00,NaN,2015-11-26 00:00:00,2018-05-10 20:53:37,7.86,0.0,1847

In [22]:
ual.head()

,username,anime_id,my_watched_episodes,my_start_date,my_finish_date,my_score,my_status,my_rewatching,my_rewatching_ep,my_last_updated,my_tags
0,karthiga,21,586,0000-00-00,0000-00-00,9,1,NaN,0,2013-03-03 10:52:53,NaN
1,karthiga,59,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-10 13:54:51,NaN
2,karthiga,74,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-04-27 16:43:35,NaN
3,karthiga,120,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-03 10:53:57,NaN
4,karthiga,178,26,0000-00-00,0000-00-00,7,2,0.0,0,2013-03-27 15:59:13,NaN

## User

In [10]:
users['year_of_birth'] = users['birth_date'].apply(lambda x:int(x[:4]))

In [11]:
users['year_of_birth'].describe()

count    108711.000000
mean       1992.874180
std           4.632399
min        1969.000000
25%        1990.000000
50%        1993.000000
75%        1996.000000
max        2008.000000
Name: year_of_birth, dtype: float64

In [12]:
users.location.value_counts().head(50) # very messy, let's use exact match for the simplicity of this poc

Poland                     1656
Germany                    1132
Brazil                     1022
Canada                      900
California                  848
France                      787
Philippines                 703
Sweden                      661
Portugal                    639
England                     574
Singapore                   566
Finland                     548
Australia                   529
Brasil                      484
Netherlands                 474
The Netherlands             460
Norway                      445
Texas                       427
New York                    415
London                      405
Russia                      391
Italy                       378
Florida                     369
UK                          363
Manila, Philippines         352
Moscow, Russia              345
Belgium                     343
USA                         322
Indonesia                   313
Ontario, Canada             313
Denmark                     311
Romania                     299
United States               291
Spain                       280
Malaysia                    269
United Kingdom              266
New Jersey                  264
Hungary                     260
Jakarta, Indonesia          255
Israel                      252
Ohio                        241
Lithuania                   233
Sydney, Australia           232
Moscow                      231
Toronto, Ontario            222
Michigan                    218
India                       216
Los Angeles, California     214
Melbourne, Australia        213
São Paulo, Brazil           204
Name: location, dtype: int64

## ratings

In [13]:
ual.username.value_counts().describe() # 108709 valid users, 287 animes rated on average

count    108709.000000
mean        287.775502
std         314.141624
min           1.000000
25%          83.000000
50%         197.000000
75%         386.000000
max        6536.000000
Name: username, dtype: float64

In [14]:
ual.head()

,username,anime_id,my_watched_episodes,my_start_date,my_finish_date,my_score,my_status,my_rewatching,my_rewatching_ep,my_last_updated,my_tags
0,karthiga,21,586,0000-00-00,0000-00-00,9,1,NaN,0,2013-03-03 10:52:53,NaN
1,karthiga,59,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-10 13:54:51,NaN
2,karthiga,74,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-04-27 16:43:35,NaN
3,karthiga,120,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-03 10:53:57,NaN
4,karthiga,178,26,0000-00-00,0000-00-00,7,2,0.0,0,2013-03-27 15:59:13,NaN

In [15]:
ual.my_score.describe()

count    3.128403e+07
mean     4.652315e+00
std      3.931615e+00
min      0.000000e+00
25%      0.000000e+00
50%      6.000000e+00
75%      8.000000e+00
max      1.000000e+01
Name: my_score, dtype: float64

# A Graph-based system

In [79]:
import networkx as nx
from networkx import info

In [111]:
anime = anime.loc[anime['aired_from_year']>=2000] # we only focus on animes after 2016

In [112]:
anime['aired_from_year'].value_counts()

2016.0    573
2017.0    515
2015.0    496
2014.0    418
2013.0    345
2012.0    340
2011.0    317
2010.0    298
2009.0    280
2007.0    247
2008.0    236
2006.0    231
2018.0    198
2005.0    190
2004.0    184
2003.0    155
2002.0    136
2001.0    135
2000.0     83
Name: aired_from_year, dtype: int64

In [113]:
users = users.sample(n=500) # randomly select 500 users

In [114]:
ual = ual.loc[ual['username'].isin(users.username.unique())]

In [115]:
ual.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 135242 entries, 23359 to 31283681
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   username             135242 non-null  object
 1   anime_id             135242 non-null  int64
 2   my_watched_episodes  135242 non-null  int64
 3   my_start_date        135242 non-null  object
 4   my_finish_date       135242 non-null  object
 5   my_score             135242 non-null  int64
 6   my_status            135242 non-null  int64
 7   my_rewatching        108214 non-null  float64
 8   my_rewatching_ep     135242 non-null  int64
 9   my_last_updated      135242 non-null  object
 10  my_tags              8311 non-null    object
 11  score_normalized     132373 non-null  float64
dtypes: float64(2), int64(5), object(5)
memory usage: 13.4+ MB

In [116]:
B = nx.DiGraph()

# Add nodes
B.add_nodes_from(anime['anime_id'].unique(),node_type='anime')         
B.add_nodes_from(users['username'].unique(),node_type='user')

In [117]:
info(B)

'DiGraph with 5877 nodes and 0 edges'

In [118]:
all_genres = set()
for i, row in anime[['anime_id','genre']].iterrows():
    if pd.notnull(row['genre']):
        genres = row['genre'].split(',')
        for genre in genres:
            genre = genre.strip()
            if genre not in all_genres:
                all_genres.add(genre)
                B.add_node(genre,node_type='genre')
            B.add_edge(row['anime_id'],genre)

In [119]:
info(B)

'DiGraph with 5920 nodes and 18672 edges'

In [120]:
# Each anime producer specializes a few types of and attrats certain group of audience, user bondiness to the same producer/studio

all_studios = set()
for i, row in anime[['anime_id','studio']].iterrows():
    if pd.notnull(row['studio']):
        studios = row['studio'].split(',')
        for studio in studios:
            studio = studio.strip()
            if studio not in all_studios:
                all_studios.add(studio)
                B.add_node(studio,node_type='studio')
            B.add_edge(row['anime_id'],studio)

In [121]:
all_producers = set()
for i, row in anime[['anime_id','producer']].iterrows():
    if pd.notnull(row['producer']):
        producers = row['producer'].split(',')
        for producer in producers:
            producer = producer.strip()
            if producer not in all_producers:
                all_producers.add(producer)
                B.add_node(producer,node_type='producer')
            B.add_edge(row['anime_id'],producer)

In [122]:
# Season, assume people would be interested in animes that were in the same period as they liked/rated highly
# reduce the bias brought by popularity

lookup = {'Winter':'1','Spring':'2','Summer':'3','Fall':'4'}

season_lookup = {season:'-'.join([season.split()[1], lookup[season.split()[0]]]) for season in anime['premiered'].unique() if pd.notnull(season)}

sorted_season_list = sorted(list(season_lookup.values())) # chronological sequence of seasons
for i, season_code in enumerate(sorted_season_list):
    B.add_node(season_code, node_type='season')
    if i>=1:
        B.add_edge(season_code, sorted_season_list[i-1]) # connect consequent seasons together

for anime_id, season in anime[['anime_id','premiered']].values:
    if pd.notnull(season):
        B.add_edge(anime_id,season_lookup[season]) # edges that connect anime to its season

In [123]:
ual = ual.dropna(subset=['username','anime_id','my_score'])

In [124]:
ual['score_normalized'] = ual.groupby('username')['my_score'].transform(lambda x: (x - x.mean()) / x.std())

In [125]:
for user, anime_id, score, score_norm in ual[['username','anime_id','my_score','score_normalized']].values:
    if score>=5 and anime_id in list(B.nodes):
        B.add_edge(user, anime_id, weight=score_norm+1)

In [126]:
B.remove_nodes_from(list(nx.isolates(B)))

In [127]:
info(B)

'DiGraph with 7010 nodes and 107747 edges'

In [27]:
# more things to consider: temporal effect, other unpresented attributes

In [28]:
# TODO: use hockeyAI's (drafting/career choice) example as an example to illustrate how much help it can be to companies, but use this anime RS as a working example

In [128]:
damping_factor = 0.85

In [129]:
user_nodes = [n for n,v in B.nodes(data=True) if v['node_type'] == 'user']  # get a list of all users in the graph

In [130]:
from random import sample

In [131]:
active_user = sample(user_nodes, 1)[0]

In [132]:
active_user

'Via'

In [133]:
ppr_values = nx.pagerank(G=B, alpha=damping_factor, max_iter=1000, personalization={active_user:1.0}, weight='weight')

In [134]:
viewed_animes = ual.loc[ual['username']==active_user,'anime_id']

In [135]:
anime_ppr_values = {node:value for node,value in ppr_values.items() if nx.get_node_attributes(B, "node_type")[node]=='anime' and node not in viewed_animes}

In [136]:
def topn_from_dict(dic, n=10):
    """
    Returns the top-[n] highest valued items from [dic]
    """
    return sorted(dic.items(), key=lambda kv: kv[1])[::-1][:n]

In [137]:
recommendations = topn_from_dict(anime_ppr_values, 10)

In [139]:
recommendations

[(2034, 0.004653947481599848),
 (1536, 0.004653947481599848),
 (121, 0.004653947481599848),
 (322, 0.004653947481599848),
 (1535, 0.004653947481599848),
 (60, 0.004653947481599848),
 (199, 0.004653947481599848),
 (741, 0.004653947481599848),
 (918, 0.004653947481599848),
 (168, 0.004653947481599848)]

In [138]:
anime.loc[anime['anime_id'].isin([aid for aid,_ in recommendations])]

,anime_id,title,title_english,title_japanese,title_synonyms,image_url,type,source,episodes,status,...,broadcast,related,producer,licensor,studio,genre,opening_theme,ending_theme,duration_min,aired_from_year
3001,168,s.CRY.ed,s-CRY-ed,スクライド,Scryed,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,26,Finished Airing,...,Wednesdays at 18:00 (JST),"{'Adaptation': [{'mal_id': 517, 'type': 'manga...",Yomiko Advertising,"Bandai Entertainment, Sentai Filmworks",Sunrise,"Action, Sci-Fi, Adventure, Super Power, Drama","['#1: ""Reckless Fire"" by Yasuaki Ide', '#2: ""D...","['#1: ""Drastic My Soul"" by Mikio Sakai', '#2: ...",24.0,2001.0
3147,918,Gintama,Gintama,銀魂,"Gin Tama, Silver Soul, Yorinuki Gintama-san",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,201,Finished Airing,...,Thursdays at 18:00 (JST),"{'Adaptation': [{'mal_id': 44, 'type': 'manga'...","TV Tokyo, Aniplex, Dentsu, Trinity Sound, Audi...","Sentai Filmworks, Crunchyroll",Sunrise,"Action, Sci-Fi, Comedy, Historical, Parody, Sa...","['#01: ""Pray"" by Tommy heavenly6 (eps 1-24)', ...","['#01: ""Fuusen Gum"" by Captain Straydum (eps 1...",24.0,2006.0
3265,741,Sensitive Pornograph,NaN,センシティブ・ポルノグラフ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,OVA,Manga,1,Finished Airing,...,NaN,"{'Adaptation': [{'mal_id': 1507, 'type': 'mang...",Phoenix Entertainment,Media Blasters,Ajia-Do,"Comedy, Drama, Hentai, Romance, Yaoi",[],[],30.0,2004.0
3404,199,Sen to Chihiro no Kamikakushi,Spirited Away,千と千尋の神隠し,Sen and Chihiro&#039;s Spiriting Away,https://myanimelist.cdn-dena.com/images/anime/...,Movie,Original,1,Finished Airing,...,NaN,[],Toho,"Walt Disney Studios, GKIDS",Studio Ghibli,"Adventure, Supernatural, Drama","['""Day of the River/Ano hi no kawa"" by Joe His...","['""Itsumo Nando demo (Always with Me)"" by Yumi...",125.0,2001.0
3507,60,Chrno Crusade,Chrono Crusade,クロノクルセイド,Chrno Crusade: Mary Magdalene,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,24,Finished Airing,...,Tuesdays at 02:28 (JST),"{'Adaptation': [{'mal_id': 338, 'type': 'manga...","Lantis, Kadokawa Shoten, Fuji TV","ADV Films, Funimation",Gonzo,"Action, Historical, Demons, Supernatural, Romance","['""Tsubasa wa Pleasure Line (翼はPleasure Line)""...","['""Sayonara Solitaire (さよならソリティア)"" by Saeko Ch...",23.0,2003.0
3802,1535,Death Note,Death Note,デスノート,DN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,37,Finished Airing,...,Wednesdays at 00:56 (JST),"{'Adaptation': [{'mal_id': 21, 'type': 'manga'...","VAP, Konami, Ashi Production, Nippon Televisio...",Viz Media,Madhouse,"Mystery, Police, Psychological, Supernatural, ...","['#1: ""the WORLD"" by Nightmare (eps 1-19)', '#...","['#1: ""Alumina"" by Nightmare (eps 1-19)', '#2:...",23.0,2006.0
4223,322,Paradise Kiss,Paradise Kiss,Paradise kiss,ParaKiss,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,...,Fridays at 00:35 (JST),"{'Adaptation': [{'mal_id': 29, 'type': 'manga'...","Aniplex, Fuji TV",Geneon Entertainment USA,Madhouse,"Slice of Life, Comedy, Drama, Romance, Josei","['""♥Lonely in Gorgeous♥"" by Tommy february6']","['""Do You Want To"" by Franz Ferdinand']",24.0,2005.0
5112,121,Fullmetal Alchemist,Fullmetal Alchemist,鋼の錬金術師,"Hagane no Renkinjutsushi, FMA, Full Metal Alch...",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,...,Saturdays at 18:00 (JST),"{'Adaptation': [{'mal_id': 25, 'type': 'manga'...","Aniplex, Dentsu, Square Enix, Mainichi Broadca...",Funimation,Bones,"Action, Adventure, Comedy, Drama, Fantasy, Mag...","['#1: ""Melissa (メリッサ)"" by Porno Graffitti (eps...","['#1: ""Melissa (メリッサ)"" by Porno Graffitti (ep ...",24.0,2003.0
6419,1536,Busou Renkin,Buso Renkin,武装錬金,"BoRe, BuRe, Arms Alchemy",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,...,Thursdays at 01:00 (JST),"{'Adaptation': [{'mal_id': 41, 'type': 'manga'...","Geneon Universal Entertainment, Yomiko Adverti...",Viz Media,Xebec,"Action, Fantasy, Supernatural, Comedy, School,...","['""Makka na Chikai"" by Fukuyama Yoshiki (eps 2...","['#1: ""Hoshi Akari"" by Jyukai (eps 1-14, 26)',...",24.0,2006.0
6549,2034,Lovely★Complex,Lovely Complex,ラブ★コン,"Love★Com, Love Com",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,24,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 31, 'type': 'manga'...","TBS, TAP, Sony Music Entertainment, Shueisha, ...",Discotek Media,Toei Animation,"Comedy, Romance, Shoujo","['#1: ""Kimi + Boku = Love?"" by Tegomass (eps 1...","['#1: ""Kiss ~ Kaerimichi no Love Song"" by Tego...",24.0,2007.0

# Script code

In [ ]:
class User:
    def __init__(self, username):
        self.username = username
        self.viewed_animes = []
    
    def get_viewed_anime_list(self):
        return self.viewed_animes

In [ ]:
class Recommender:
    def __init__(self):
        self.graph = None
        pass

    def build_graph(self, users, animes, ual):
        B = nx.DiGraph()
        
        # Add nodes
        B.add_nodes_from(animes['anime_id'].unique(),node_type='anime')         
        B.add_nodes_from(users['username'].unique(),node_type='user')
        
        all_genres = set()
        for i, row in animes[['anime_id','genre']].iterrows():
            if pd.notnull(row['genre']):
                genres = row['genre'].split(',')
                for genre in genres:
                    genre = genre.strip()
                    if genre not in all_genres:
                        all_genres.add(genre)
                        B.add_node(genre,node_type='genre')
                    B.add_edge(row['anime_id'],genre)
        
        all_studios = set()
        for i, row in anime[['anime_id','studio']].iterrows():
            if pd.notnull(row['studio']):
                studios = row['studio'].split(',')
                for studio in studios:
                    studio = studio.strip()
                    if studio not in all_studios:
                        all_studios.add(studio)
                        B.add_node(studio,node_type='studio')
                    B.add_edge(row['anime_id'],studio)
    
    def run_user(self, active_user, damping_factor):
        ppr_values = nx.pagerank(G=self.graph, alpha=damping_factor, max_iter=1000, personalization={active_user:1.0}, weight='weight')
        anime_ppr_values = {node:value for node,value in ppr_values.items() if nx.get_node_attributes(B, "node_type")[node]=='anime' 
                            and node not in active_user.get_viewed_anime_list()}
        return topn_from_dict(anime_ppr_values, 10)

# Widget

In [141]:
from ipywidgets import widgets, interact, Layout
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from IPython.display import display, clear_output

In [147]:
interested_quarters = ['2022-03-31', '2022-06-30']

box_layout = Layout(
    display="flex",
    flex_flow="row",
    align_items="center",
    width="100%",
    justify_content="center",
)

all_careerareas = ['All'] + [resp for resp in ['1','2']]
careerarea_widget = widgets.Dropdown(
    options = all_careerareas,
    value = '1',
    description = 'Career Area: ',
    layout={'width': 'initial'},
    style = {'description_width': 'initial'},
    rows = 10
)

region_widget = widgets.Dropdown(
    options = sorted([resp for resp in ['a','b']]),
    value = 'a',
    description = 'Location: ',
    layout={'width': 'initial'},
    style = {'description_width': 'initial'},
    rows = 10
)

row_1 = widgets.HBox([careerarea_widget, region_widget], layout = box_layout)
# out = widgets.interactive_output(run_growth_trends, {'career_area':careerarea_widget, 'location': region_widget})
display(row_1)
# display(out)

HBox(children=(Dropdown(description='Career Area: ', index=1, layout=Layout(width='initial'), options=('All', …